### ISSUE TITLE
Getting provider issue on auth

### ISSUE THREAD

**Issue by rakin92** [cmelgarejo/go-gql-server#1]
I followed part 4 tutorial set up google Oauth2 and have my PROVIDER_GOOGLE_KEY and PROVIDER_GOOGLE_SECRET set in .env file

when I go to `http://localhost:7777/v1/auth/google`

I get this message `you must select a provider`

Assuming it is being raised from goth since no reference found in this repo.
Also in `cmd/gq'-server/main`  missing `Scopes:    strings.Split(utils.MustGet("PROVIDER_GOOGLE_SCOPES"), ","),`

I am running `sh scripts/build.sh` followed by `sh scripts/run.sh` to run the service. As I was having trouble running the dev-run script due to some issues I am having with realize.

**Comment by cmelgarejo** [comment]
Woah, I have overlooked this project for so long, sorry @rakin92 
But this all should be fixed in the current master branch, it was a problem on the context keys for the goth library, I'm marking this as solved. thanks! 👍
